chore: only allow releasing from release branches
This changes the release so that only release branches in the form of release/v0.y are accepted.

It changes the release Branch creation into a "Release Branch Cutoff". This leads to us only having one point in which the version file is bumped for y-streams (0.17,0.18. etc.).

During the release this file is touched up only to remove the -dev suffix after which the tag is pushed.

For z-streams (0.17.z) a new commit with a bump is still needed this is not included yet.

diff --git a/.github/workflows/release-branch.yaml b/.github/workflows/release-branch.yaml
--- a/.github/workflows/release-branch.yaml
+++ b/.github/workflows/release-branch.yaml
@@ -18,6 +18,7 @@ jobs:
       repository-projects: read
     outputs:
       minor: ${{ steps.get-minor.outputs.minor }}
+      branch: ${{ steps.verify-branch.outputs.branch }}
     steps:
       - name: Generate token
         id: generate_token
@@ -57,6 +58,18 @@ jobs:
           fi
           echo "release-notes-file=$f" >> $GITHUB_ENV
           echo "release-notes-file=$f" >> $GITHUB_OUTPUT
+      - name: Verify Branch does not exist
+        id: verify-branch
+        run: |
+          set -e
+          minor="v${{ steps.get-minor.outputs.minor }}"
+          branch="releases/$minor"
+          if git ls-remote --exit-code origin refs/heads/$branch ; then
+            >&2 echo "branch $branch already exists, aborting"
+            exit 1
+          fi
+          echo "branch $branch does not exist"
+          echo "branch=$branch" >> $GITHUB_OUTPUT
 
   create-branch:
     runs-on: ubuntu-latest
@@ -82,26 +95,7 @@ jobs:
       - name: Create Release Branch
         run: |
           set -e
-          git config --global user.name github-actions
-          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
-          
-          minor="v${{ needs.cutoff-preconditions.outputs.minor }}"
-          
-          if ! [[ "$tag" =~ ^v?[0-9]+\.[0-9]+$ ]]; then
-            >&2 echo "no valid release branch minor $minor: it has to be of the form '^v?[0-9]+\.[0-9]+$'"
-            exit 1
-          fi
-          
-          
-          branch="releases/$minor"
-          
-          if git ls-remote --exit-code origin refs/heads/$branch ; then
-            >&2 echo "branch $branch already exists, aborting"
-            exit 1
-          fi
-          
-          echo "creating release branch: $branch"
-          
+          branch=${{ needs.cutoff-preconditions.outputs.branch }}
           git checkout -b "$branch"
           git push origin $branch
   bump-main-pr:
